# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'clonestagram' do
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for clonestagram

pod 'Alamofire'
pod 'Kingfisher', '~> 7.0'
end
